"""added fields in member table

Revision ID: e674063700d9
Revises: 726a95b809e7
Create Date: 2026-07-13 02:15:59.311961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e674063700d9'
down_revision: Union[str, Sequence[str], None] = '726a95b809e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_enum = postgresql.ENUM(
    'Maid',
    'Driver',
    'Cook',
    'Gardner',
    'House_Manager',
    'Nanny',
    'Dog_Walker',
    'Maintenance',
    'Security',
    'Family',
    'Friend',
    'NONE',
    name='role',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('members', sa.Column('contact_name', sa.String(), nullable=True))
    op.add_column('members', sa.Column('description', sa.String(), nullable=True))
    op.add_column('members', sa.Column('nick_name', sa.String(), nullable=True))
    op.add_column(
        'members',
        sa.Column('role', role_enum, server_default='NONE', nullable=False),
    )
    op.alter_column('members', 'role', server_default=None)
    op.add_column('members', sa.Column('user_description', sa.String(), nullable=True))
    op.drop_column('members', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('members', 'user_description')
    op.drop_column('members', 'role')
    op.drop_column('members', 'nick_name')
    op.drop_column('members', 'description')
    op.drop_column('members', 'contact_name')
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
