"""changed preferred_language user nonnullable

Revision ID: cbca9b88e48a
Revises: 5b3d93f73b8c
Create Date: 2026-07-17 20:45:52.750902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbca9b88e48a'
down_revision: Union[str, Sequence[str], None] = '5b3d93f73b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
